export const verifyUser = async (req, res, next) => {
    try {
        
    } catch (error) {
        console.log(error);
    }
}